OPENAI_API_KEY="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"
GWDG_API_KEY="0631b5687db0129ab90a12f72c6e3e1c"
BASE_URL="https://chat-ai.academiccloud.de/v1"
BASE_URL_EMBEDDINGS="https://chat-ai.academiccloud.de/v1/embeddings"